[api]
# Get your API key from: https://platform.openai.com/api-keys
key = ""

[chat]
# For details see: https://platform.openai.com/docs/api-reference/chat
model = "gpt-4o"
max_tokens = { value = 4096, min = 128, max = 4096, step = 128 }
temperature = { value = 1.0, min = 0.0, max = 1.0, step = 0.05 }
top_p = { value = 1.0, min = 0.0, max = 1.0, step = 0.05 }
frequency_penalty = { value = 0.0, min = -2.0, max = 2.0, step = 0.05 }
presence_penalty = { value = 0.0, min = -2.0, max = 2.0, step = 0.05 }

[ui]
editor_command = ["gedit", "--standalone"]

[ui.colors]
conversation.background = "#020414"
conversation.foreground = "#33DD88"
conversation_names = "#DD4400"
prompt.background = "#110000"
prompt.foreground = "#DDCC04"
config.background = "#020414"
config.foreground = "#FF5511"
debug.background = "#020414"
debug.foreground = "#5511FF"

[hotkeys]
quit_program = [ {code = { Char = "q" }, modifiers = "CONTROL"} ]
select = [ { code = "Enter", modifiers = "NONE" } ]
cancel = [ { code = "Esc", modifiers = "NONE" } ]
new = [ { code = { Char = "n" }, modifiers = "CONTROL" } ]
clear = [ { code = { Char = "c" }, modifiers = "CONTROL" } ]
selection_up = [ { code = "Up", modifiers = "NONE" } ]
selection_down = [ { code = "Down", modifiers = "NONE" } ]
scroll_up = [ { code = "PageUp", modifiers = "NONE" } ]
scroll_down = [ { code = "PageDown", modifiers = "NONE" } ]
increment = [ { code = { Char = "=" }, modifiers = "NONE" } ]
decrement = [ { code = { Char = "-" }, modifiers = "NONE" } ]
cycle_tab = [ { code = "Tab", modifiers = "NONE" } ]
view_conversation_tab = [ { code = { F = 1 }, modifiers = "NONE" } ]
view_config_tab = [ { code = { F = 2 }, modifiers = "NONE" } ]
view_debug_tab = [ { code = { F = 3 }, modifiers = "NONE" } ]
send_prompt = [ { code = "Enter", modifiers = "ALT" } ]
get_message_from_editor = [ { code = { Char = "e" }, modifiers = "ALT" } ]

[[system.instructions]]
name = "simple"
message = """
You are a helpful assistant.
Do not bother being polite. Your responses should be concise and terse.
"""

[[system.instructions]]
name = "detailed"
message = """
You are a helpful assistant.
Do not bother being polite. Your responses should be detailed.
"""

[[system.instructions]]
name = "funny"
message = """
You are a funny assistant.
Do not bother being polite. Your responses should be funny.
"""
