[api]
# Get your API key from: https://platform.openai.com/api-keys
key = ""

[chat]
# For details see: https://platform.openai.com/docs/api-reference/chat
model = "gpt-4o"
max_tokens = 4096
temperature = 1.0
top_p = 1.0
frequency_penalty = 0
presence_penalty = 0

[ui]
editor_command = ["gedit", "--standalone"]

[ui.colors]
conversation.background = "#020414"
conversation.foreground = "#33DD88"
conversation_names = "#DD4400"
prompt.background = "#110000"
prompt.foreground = "#DDCC04"
config.background = "#020414"
config.foreground = "#FF5511"
debug.background = "#020414"
debug.foreground = "#5511FF"

[hotkeys]
quit_program = [ {code = { Char = "q" }, modifiers = "CONTROL"} ]
select = [ { code = "Enter", modifiers = "NONE" } ]
cancel = [ { code = "Esc", modifiers = "NONE" } ]
new = [ { code = { Char = "n" }, modifiers = "CONTROL" } ]
selection_up = [ { code = "Up", modifiers = "NONE" } ]
selection_down = [ { code = "Down", modifiers = "NONE" } ]
scroll_up = [ { code = "PageUp", modifiers = "NONE" } ]
scroll_down = [ { code = "PageDown", modifiers = "NONE" } ]
cycle_tab = [ { code = "Tab", modifiers = "NONE" } ]
view_conversation_tab = [ { code = { F = 1 }, modifiers = "NONE" } ]
view_config_tab = [ { code = { F = 2 }, modifiers = "NONE" } ]
view_debug_tab = [ { code = { F = 3 }, modifiers = "NONE" } ]
send_prompt = [ { code = "Enter", modifiers = "ALT" } ]
get_message_from_editor = [ { code = { Char = "e" }, modifiers = "ALT" } ]
increment_tempurature = [ { code = { Char = "t" }, modifiers = "NONE" } ]
decrement_tempurature = [ { code = { Char = "t" }, modifiers = "SHIFT" } ]
increment_top_p = [ { code = { Char = "p" }, modifiers = "NONE" } ]
decrement_top_p = [ { code = { Char = "p" }, modifiers = "SHIFT" } ]
increment_frequency_penalty = [ { code = { Char = "f" }, modifiers = "NONE" } ]
decrement_frequency_penalty = [ { code = { Char = "f" }, modifiers = "SHIFT" } ]
increment_presence_penalty = [ { code = { Char = "r" }, modifiers = "NONE" } ]
decrement_presence_penalty = [ { code = { Char = "r" }, modifiers = "SHIFT" } ]

[[system.instructions]]
name = "simple"
message = """
You are a helpful assistant.
Do not bother being polite. Your responses should be concise and terse.
"""

[[system.instructions]]
name = "detailed"
message = """
You are a helpful assistant.
Do not bother being polite. Your responses should be detailed.
"""

[[system.instructions]]
name = "funny"
message = """
You are a funny assistant.
Do not bother being polite. Your responses should be funny.
"""
