# For details see: https://platform.openai.com/docs/api-reference/chat

[api]
key = ""

[chat]
model = "gpt-4o"
max_tokens = 4096
temperature = 1.0
top_p = 1.0
frequency_penalty = 0
presence_penalty = 0

[ui]
editor_command = ["gedit", "--standalone"]

[[system.instructions]]
name = "simple"
message = """
You are a helpful assistant.
Do not bother being polite. Your responses should be concise and terse.
"""

[[system.instructions]]
name = "detailed"
message = """
You are a helpful assistant.
Do not bother being polite. Your responses should be detailed.
"""

[[system.instructions]]
name = "funny"
message = """
You are a funny assistant.
Do not bother being polite. Your responses should be funny.
"""
