name: Rust CI
on:
  push:
    branches: "**"
env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust
      uses: Swatinem/rust-cache@v2

    - name: Check code formatting
      run: cargo fmt -- --check

    - name: Check clippy
      run: cargo clippy -- -D warnings

    - name: Run tests
      run: cargo test
